# Generated by Django 5.2.5 on 2025-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tag',
            field=models.ManyToManyField(related_name='blogstag', to='blog.tags'),
        ),
    ]
