# Generated by Django 5.2.5 on 2025-08-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_title_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(default='something', max_length=400),
        ),
    ]
