# Generated by Django 5.2.5 on 2025-08-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.CharField(help_text='مثلا /about/ یا یک url کامل', max_length=300, verbose_name='link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordering ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
